version: "3.8"
services:

  db:
    image: postgres
    container_name: pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: bartekkobala@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  cache:
      image: redis:6.2-alpine
      restart: always
      ports:
        - '6379:6379'
      volumes: 
        - cache:/data

volumes:
  local_pgdata:
  pgadmin-data:
  cache:
    driver: local

networks:
  default:
    external:
      name: iot
